FROM node:18-alpine AS development

WORKDIR /app/frontend

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm 
RUN pnpm config set store-dir /app/frontend/.pnpm-store
RUN pnpm install

COPY . .

EXPOSE 8080

CMD ["pnpm", "dev"] 