
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/trustwise_db
    depends_on:
      - db
    volumes:
      - ./api:/app
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          ignore:
            - __pycache__
            - .git/
            - .gitignore
            - "*.pyc"

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trustwise_db
    volumes:
      - db_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend:cached
      - frontend_node_modules:/app/frontend/node_modules
    depends_on:
      - api


volumes:
  db_data:
  frontend_node_modules: